language: python
python:
- 3.9
install:
- pip install -r requirements.txt
script:
- black --check .
- flake8 --max-line-length=99 .
- coverage run manage.py test
after_script:
- coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: $REGION
  app: swe1-app
  env: django-env
  bucket_name: $BUCKET_NAME
  on:
    repo: sarthakgoel1997/swe1-app
    branch: main
  skip_cleanup: 'true'
