language: python

python:
  - 3.9

install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 --max-line-length=99 .
  - coverage run manage.py test

after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "FzDBtHO20nnn4dgLeT60NSQYUngtllEaJkk4P5pWNb2snY2nvxwSviCAWSD6KetNAHu9xlidZpJRUsKcDC32poLk4L8yBuQ9ookS6P29S93ca1nokze3oUof1qHIPsddloK+4ANlCU1kId9SlVc0UlGZT8+bWVOm0HET6yYHXp1xR9An9kq6QJ2IGmcMBmUkyhe4orR6Bo/rK5tI8WE6/72RwS359nzuHXDCpuzigOvu8sJhG2jH046eJ6A9lu52h8EgY4aBWXMd1oH0b8azWwglzySEcxe70qAvH3nF1Yv+D9kPUpeNndhrmtWIxjYruBIPJoofiCeexsg6MBdfV24wxWoI6UoDpWrgGDaYt8P4o0vmjFDQGezsvCnIFt7JHnCgyxqyRxfA0WDEqt84bHDem+HkDWCSj43DTqP/D1xFHQ1tMQRZlO4BZQMToTVMW/C6LMGdfVC1eL8oAcG1vN1bDOud+t4lzo8rHHkTA1bVuKv/PffjQ0ngaxCt9cKMFCBteVA7/Ouacxrd27K9Jj47W2wo0h9GvywvY3i+xm00o0NShm6qDQ3Jg5O58rTKow8JuB4+3+tKKoCVYIFvEWbKJsMNIs/OlEvXBDIAnM8prkb7VRhCgs5iAsI+fTWOUV1vSRBj6O8UyDzmXjHN5ywusebaRwINxVa8riiBoWE="
  secret_access_key:
    secure: "pyNpwTO0I6fykMXyUL/qU2dfFuRza+3NpwqkzlD8Xgab4DDJANCV3vze60bdtFoA9sSDHTaUWmkI1fy0w0+ngkJBVlDHr0LGQDhac102ZF+OmQ5iPISNSm+1oRJRCcUzQ7pEQWaHNryFhgf4y9kHSQJQdmll/Ab8C97W4fyPvxcWLAwLXHtohQ533HTWC3ekAnybjT1xGsAAyxyh2bHBuepNxx//8tSBwNBfEGuJjzJFpkCOXJQNXNOH9F0nU3/1FPCnf0y+2HESpG4+gaL1hKKUyzAd/7PQV9e6MYArQ0cZ1qf5/6Y9TfMrwlzi3SgfuZoI/L5GqzHXFYPqPSpwuXYF82dM+IU73tTgndN0HZjgSftNspqvDxlibk0mg4EWH9MXoW5cn3+GuX0l2SRHZOuePNmfsb6JVRCmAUYGp0A6p6K/qFD73dN6YmyrsvvW6iwCqi5vhItK7ccfflGzkx+8QLBpZtJjHNqbc64YAhRICydr+tPKKaQ/MW94SI5Uu7JAjhV8MAh2N2ch2Jhu0XuqMPSlXPpWZsUZXnHoqaJkfPJAfY6cBc+H+g+DbZamNFoYAhu1btCaTBQO7Zlo2N8cxJMc/XROV3bVEJYAJHxA+ofAcjDo+hhAso31WZLD8Te50SAOCNpNXe4Bfc/x2iyDu1ZpTsn1u3IDUVVz0V0="
  region: "us-west-2"
  app: "swe1-app"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-638237791383"
  on:
    branch: main
