language: python

python:
  - 3.9

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "lTX37r0nO6UlSpIFB27263+vAdXyRhlFLkyJbPY9tbjq3tr0TSlRx5BtOQ/4fg+XKovf4zS0rq+6Lq1M7iAquKGUm2Qbb1/8a4q+fGMVSzTsNheHHqSg3mC9BWq3DiA6D6VDqmgAMCZYTLEpVkc1C7ByT9jtIW7DkP9G/T1+zsTiKNq04cDFA7/U5hj15Ov8k1i/S4UdvUi9eH5c4tlcMeX9RSof0Mo/Vk8dSnv0g3TWOFn3lcyQdr82QBz29+RDKkq6k9YVhGv4gJ7x0rAw7y++v6cJP5LRq+NNgwQXAO9W2tq1sf30sPhFw8RoJjz32CNDqpxTo9EaS7G9jMVtJtcJHHoJ3I3JwDkdthXAbr4MHt0ql3rXDFV3Aeo3qA16qMD1PADiyf4YTDTYbLA6KqUdviGFpHWSQOiGrTX/D/mbWUVmIEIi3k9SIAYBRMmBWxARAHAOCFEisJbufKGXinyVNjkROeN0gncub1TflxS+UfccoLy7rEUUskIbbocAqXEa9oPFU+PBljKydjcuhfZ7Ki0PcBGMNIrgyGKDq8H4fzurIJUpWb40jhfgQtGhMq6EKgLVfoW9CN0XqjPiU72vc8u1C+ojaEsiraGQmTXAWWdCPQNLamul0bg0ZXGj44oO55eV1iTS+eAt+hDH2HoIAy5VHsp/ACJm704n09Q="
  secret_access_key:
    secure: "OWUKEj/oXdFx8N561AQROzyQrUraK0p2kd3aIIAuiLp3L5R0+Gbkihc5Qlj1fad4ZM9Scm46RI/u+zMgiMgpqYGBSP9suJbsW+VX1xCNRTS8rSIEdM4Xc/4WjNWZ/lQUdEzSF3ITlD5uIlrrQ7cr+sk5nMxG8pXx7UPlNubhuzrqQzyIwPnTfvGeI8+0J2sPo4GoolZxzjMKhGXyRUZRGCYoeyd+powMypWduHFt2vjmwAkx3qPlkuk2Wz9Oplk6s2gS9XQKpzLaUNIPywJZi+n/IplgPwHI1ZpvEARzYjPZ6DB7BbB4yl4aR3/u7iQkRMyv2XrENScByRj3phq0CpRv7QA/M/YUphAMUiC5IWIcw83pVXGzyxij7JXlXWe5f20qITK1zRFSdTAQuK75bDvhEEgdWaQLdUx9AInY8ZcLdo/xbgkS+1zrppATLInEqGIQxORtYsPubCx7xeDMa7pr8HDW2nAtpha77Kmp/VGjkSqBx4ewYCPt3a8hP/9oseJWyXZTUU5FFnp4+yxDOaHGwEZmGK3lY+cda4NUiTK5Wcw3uK7Jh9kGqX6YXIGbfPCY+HtyEp4H0lyTT+o1z6UmFxMlS6ZGTx1eCBTDBDWMVvaICCA3eU5E+xaLcl26dT2KNI7YOYx/Eq953H8jTxEw4yNaLjrTwykuD8Bt/T0="
  region: "us-west-2"
  app: "swe1-app"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-638237791383"
