language: python
python:
- 3.9
install:
- pip install -r requirements.txt
script:
- black --check .
- flake8 --max-line-length=99 .
- coverage run manage.py test
after_script:
- coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAZJGPP2SLYSWSGK7C
  secret_access_key:
    secure: fUMNqlACXj2CQDnWGXIrcGtQYpdxejQHmLZyMgwqa2OYs9Z+yh959l1kMF7y8Hvn1gN0xmPKJ+HFL/Zy2ikGdc18eHKuOMLY+TAwy4icu6FnwcFRTN50XgLpwytmaBuILjs5UXuyJ6KT2Llx7ypgQIoheQtJMopqeISs0/26NekT8LpnG0ho4x8eElHgZLQveXz8atsWDpAJxTfVljIIj/n4Zvk8C8DxSxCnZCTH330LTid1HXH6CYm+vYfft2O4WEG9aqTRrOhX1YdA935aY8I4vi0EMBJ6UEYam+HCJf1kkH7iPaNtaMnWFHhNX+GNI6sh//fWXNp5oKYBn2pJOlXIwBz6rudei2IR1dadg6CRuEBV4s+IAAXmYXtrBtDYpUGsBMH3B/s2/Z2bS4VE8wgWEzOogyjAs0D0aoy2o7V0MAEImbuEtto1RQHHzUhFcRzbBO4VX8IttaHCgWJBidM+RZs3CT9v1zXv0HY2u1Eye8ic39WKHmI3PePE43RwqK38TzraGsMfOY1nyY/YimjR3MGrEn0dAa0vUpdchKntdN2+UCjNhxG3+a2kOQBcj9JRKRlthmMVwSNS9/E/DKtW/+5fqxJzIOPl+02fqSM9w72IPlx9qdnmveyUuqF9yymo8wDPfknAIm/feuL7WcMGoyncq0mhPI/n9RHtRhI=
  region: us-west-2
  app: swe1-app
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-638237791383
  on:
    repo: sarthakgoel1997/swe1-app
    branch: main
  skip_cleanup: 'true'
